### ISSUE TITLE
Sometimes it incorrectly returns citations number to be zero.

### ISSUE THREAD

**Issue by cowpa** [beloglazov/zotero-scholar-citations#10]
Sometimes it returns citation number to be zero which is incorrect. The number is not zero when I search on google. 

For example,
"Optimal Value of Information in Graphical Models"
"Active Sensing for Robotics - A Survey"

**Comment by beloglazov** [comment]
Does it always return zero for the first item? I've just tried it, and it fetches the citations correctly. I can't find the second item by title in Scholar.

**Comment by cowpa** [comment]
Yes, but I guess I know why. There is something wrong with the first item: first author is wrong in google scholar. And we cannot find the second item in scholar. 
I am curious where the citation number from (this seems more reliable) when we just use google, rather than google scholar, to search the title.

**Comment by cowpa** [comment]
Yes, you'r right. I guess I know why. There is something wrong with the first item: first author is wrong in google scholar (I found more of such mistakes). And we cannot find the second item in scholar. 
I am curious where the citation number from when we just use google (rather than google scholar) to search the title.

**Comment by beloglazov** [comment]
When you just search the second one in Google by title, it shows citations for other articles that have matching words in their titles. I don't see the exact match for this title.

Regarding the first one, you can try to delete it from Zotero and then re-add from Scholar using the "Save to Zotero" icon on the right side of the address bar in Firefox. That should create a correct entry with citations.

**Comment by cowpa** [comment]
May I know which link you are using for saving the entry? I tried several one. None works.

**Comment by beloglazov** [comment]
First, go to this page: http://scholar.google.com.au/scholar?hl=en&q=Optimal+Value+of+Information+in+Graphical+Models&btnG=&as_sdt=1%2C5&as_sdtp=

Then, on the right side of the address bar in Firefox you'll see a small icon looking like a folder. Press on it, then select the first item in the list and click OK. That should add it to your Zotero library and populate the number of citations in the Extra field.

**Comment by cowpa** [comment]
Thanks a lot. I guess the problem is because Google scholar stored an incorrect entry in its database. (You can see the name list of the authors is inconsistent with the pdf file, while the second entry is the correct one.)

**Comment by beloglazov** [comment]
No problem, I'm glad it's resolved.
