### ISSUE TITLE
Update citation count without changing "Last modified" date 

### ISSUE THREAD

**Issue by gustavdelius** [beloglazov/zotero-scholar-citations#11]
Would it be possible to update the citation count without updating the "Last modified" date field? I like to use the "last modified" date to keep track on when I last modified a reference myself. The citation count on the other hand I like to do in bulk for an entire collection and if that updates the last modified date then that field for me looses its information.

**Comment by beloglazov** [comment]
Unfortunately, I don't think that's possible. From the plugin side, there is no control over the "Last modified" date, it gets updated automatically internally whenever an item is saved.
