### ISSUE TITLE
Retrieve the list of references citing the item

### ISSUE THREAD

**Issue by fBedecarrats** [beloglazov/zotero-scholar-citations#14]
Many thanks for this plugin, very useful to analyse the visibility/impact of publications. In order to analyse further, it would be great to be able to retrieve the list of references citing the zotero item. This could be in the extra field, or even preferably in a note.
Do you think developing this kind of functionality would be desirable and doable? If so, I would be eager to give it a try and a few recommendations/ guidance would be useful.
Regards,
FB

**Comment by beloglazov** [comment]
Thanks for your feedback and suggestion! I understand that this functionality can be useful, however this is a completely new feature requiring a significant development effort, which at the moment I'm not able to commit to. I'll keep this issue open as a potential future enhancement.

**Comment by beloglazov** [comment]
I don't think this will be implemented as a part of this add-on, so I'm closing this issue.

**Comment by fBedecarrats** [comment]
Understood, thank you.

2015-12-25 2:52 GMT+01:00 Anton Beloglazov <notifications@github.com>:
