### ISSUE TITLE
Display number without leading zeros

### ISSUE THREAD

**Issue by melat0nin** [beloglazov/zotero-scholar-citations#15]
This is a great addon but I find the leading zeros rather distracting (e.g. 00014 instead of just 14). Is it possible to hide the leading zeros?

Many thanks!

**Comment by beloglazov** [comment]
Thanks for your feedback! The content of fields is interpreted as strings and leading spaces are automatically removed. That's why, to enable sorting by the number of citations, the leading zeros are required at the moment, unfortunately.
