### ISSUE TITLE
Incorrect Call Numbers

### ISSUE THREAD

**Issue by t2d** [beloglazov/zotero-scholar-citations#16]
For me, your plugin only returns call numbers like "TK5102.85 .N53 2002" or "HB172 .E39846 2015".
Maybe Google changed the API?

**Comment by beloglazov** [comment]
This looks like actual call numbers of the items. A while ago I've switched from using the Call Number column to the Extra column. Please enable displaying the Extra column and see if it contains the correct citation counts.

**Comment by t2d** [comment]
Yes, it does.
