### ISSUE TITLE
Retrieve not from Scholar

### ISSUE THREAD

**Issue by KOLANICH** [beloglazov/zotero-scholar-citations#17]
It'd be good to retrieve not from scholar, but from "export citation" link of publishers. To do it you can look for doi in pdf then use dx.doi.org to get publisher's page url, then either apply custom function for retrieving from well-known publishers, or try to load the page and find bibtex in the source using regex.

**Comment by beloglazov** [comment]
It's quite complex and I'm not sure how much better that would be. I don't think I'm going to work on this. Thanks for the suggestion though.
