### ISSUE TITLE
It doesn't support new google tick recaptcha.

### ISSUE THREAD

**Issue by KOLANICH** [beloglazov/zotero-scholar-citations#18]

**Comment by amrino** [comment]
Google changed their scholar site to "https://scholar.google.com/", but the default site of the google scholar in the plugin is still "http://scholar.google.com/". How I can change that?

**Comment by beloglazov** [comment]
Does it make it fail? Sorry, I'm not currently using the addon and can't test it right now.

**Comment by amrino** [comment]
Yes, it failed to get the data. I changed the "http" to "https", it doesn't popup warning, but still doesn't renew the data.

**Comment by beloglazov** [comment]
Do you mean you tried changing the scheme here https://github.com/beloglazov/zotero-scholar-citations/blob/master/chrome/content/scripts/zoteroscholarcitations.js#L119 and it hasn't helped?

**Comment by amrino** [comment]
Yes, I changed it. It only stoped from poping up warnnings and redrescting to google scholar page which can not be able to access to. But the citation number doesn't show, no data in "Call Number"  column.

**Comment by beloglazov** [comment]
I've just tested the current version of the add-on with Firefox 43.0.2 and it seems to work fine including handling the captcha.
