### ISSUE TITLE
Request support for Zotero 5.0

### ISSUE THREAD

**Issue by alanlivio** [beloglazov/zotero-scholar-citations#24]
Since last year Zotero 5.0 is in beta[1].
Would be great if the scholar citation plugin support the Zotero 5.0.

[1] https://forums.zotero.org/discussion/59829/zotero-5-0-beta.

**Comment by greatleapingcrab** [comment]
+1 vote here. 
But not holding my breath, since the last commit was over 2 years ago...

**Comment by beloglazov** [comment]
Unfortunately, I don't think I'll have time for this in the near future (especially because I'm not using the plugin myself anymore). But I'd be happy to accept PRs.

**Comment by srattansen** [comment]
would also really appreciate this for zotero 5.0 :)  I'm doing a massive lit. review and having all the google scholar citations would be super helpful!

**Comment by alanlivio** [comment]
The Zotero 5.0 was released recently[1].

[1] https://github.com/zotero/zotero/releases

**Comment by srattansen** [comment]
Yep...but this addon doesn't work with it? Or am I doing something wrong.

**Comment by beloglazov** [comment]
Does this build work for you guys? 

https://github.com/beloglazov/zotero-scholar-citations/raw/master/builds/zotero-scholar-citations-1.9.2-fx.xpi

**Comment by alanlivio** [comment]
I'm using Zotero 5.0.7.
The build not worked for me. I loaded the xpi, and simply Zotero do nothing. It should ask to be restart.

![screenshot from 2017-07-27 01-14-15](https://user-images.githubusercontent.com/604808/28654290-76502d92-7269-11e7-9d31-594a8829d227.png)
![screenshot from 2017-07-27 01-14-02](https://user-images.githubusercontent.com/604808/28654291-76514fce-7269-11e7-9044-367ae9cc115b.png)

**Comment by srattansen** [comment]
Sorry, it doesn't work for me. I get the same error: "The add-on "Zotero Scholar Citations" could not be installed. It may be incompatible with this version of Zotero." This is for Zotero 5.0.7.

But thanks for trying to get it working!

**Comment by greatleapingcrab** [comment]
Likewise. It loaded on an oldish version of 5.0x (not sure which) before Standalone updated itself, and then was disabled after the update to 5.08b. A fresh install of 5.07 won't let the xpi be installed.

**Comment by beloglazov** [comment]
Thanks for your quick responses! I'll re-upload soon.

**Comment by beloglazov** [comment]
I've made a few more fixes, here is the updated version: https://github.com/beloglazov/zotero-scholar-citations/raw/master/builds/zotero-scholar-citations-1.9.2-fx.xpi

**Comment by srattansen** [comment]
It works! Thanks so much for updating this. It will be very cool to have a list of all the google scholar citations in the literature review I'm writing. Will make sure to cite this useful addon :-)

**Comment by beloglazov** [comment]
Great! I'm glad you find it useful :)

**Comment by greatleapingcrab** [comment]
Thanks so much

**Comment by srattansen** [comment]
Hi - one more question - I think I blitzed Google's servers too much because I got that block thing. But the captcha doesn't show up, i.e. the browser window doesn't pop up. Is there any way to check why? When I click on URLs in Zotero, my default browser (Edge) opens okay, so it should be set up okay. When I go into Google Scholar, it works fine, so not sure how to force the captcha to come up :)

**Comment by alanlivio** [comment]
It worked for me now too. Thank you.

**Comment by beloglazov** [comment]
@srattansen here is a new version, which should fix the bug where the browser with captcha wasn't opening: https://github.com/beloglazov/zotero-scholar-citations/raw/master/builds/zotero-scholar-citations-1.9.3-fx.xpi

**Comment by sebrattansen** [comment]
Cheers mate... browser is now opening up properly. The captcha doesn't show, but that's okay I just wait 24 hours and then continue gathering citations! I have managed to do 500+ so far.

**Comment by niklasholm** [comment]
Doesn't work for Zotero 5.0.24. Refuses to install.
