### ISSUE TITLE
Compatibility with Zotero 5

### ISSUE THREAD

**Issue by KD66** [beloglazov/zotero-scholar-citations#29]
Would it be possible to use Zotero Scholar citations add-on with the new version of Zotero 5 in the near future?
Thanks, K.

**Comment by beloglazov** [comment]
The current version should already work with Zotero 5: https://github.com/beloglazov/zotero-scholar-citations/raw/master/builds/zotero-scholar-citations-1.9.3-fx.xpi

Please let me know if there are any issues.
