### ISSUE TITLE
Require date match only when there is no author info

### ISSUE THREAD

**Issue by gustavdelius** [beloglazov/zotero-scholar-citations#7]
Currently when an item has a date associated to it, the plugin restricts the Google scholar search to items with that exact date. This leads to many unmatched queries because often a publication does not have an unambiguous publication date. Often there are several sources of the article on the web with different dates. So I would recommend that the date is only used if there is no author information. I think it is safe to assume that an author will not use the same title on two different publications.

**Comment by beloglazov** [comment]
Sorry for taking so long to respond to this, I've implemented the suggested changes in 1.9.0.

**Comment by gustavdelius** [comment]
Thank you very much. I am looking forward to using it. Will it update
itself to the new version (I have automatic updating turned on) or do I
need to re-install?

----------------------------------------------------------------------
Dr Gustav W Delius, Department of Mathematics
University of York, York, YO10 5DD, United Kingdom
http://maths.york.ac.uk/www/gwd2
Tel.: +44 (1904) 323 077, Fax.: +44 (1904) 323 071, office: G/110
----------------------------------------------------------------------
http://www.york.ac.uk/docs/disclaimer/email.htm

**Comment by beloglazov** [comment]
If you are using the add-on for Firefox, it should get updated automatically.

**Comment by gustavdelius** [comment]
Thank you. I am using the stand-alone zotero and therefore just
reinstalled. The plugin now finds citation information for many of the
books that it did not find the information for in the past. That is very
good.

----------------------------------------------------------------------
Dr Gustav W Delius, Department of Mathematics
University of York, York, YO10 5DD, United Kingdom
http://maths.york.ac.uk/www/gwd2
Tel.: +44 (1904) 323 077, Fax.: +44 (1904) 323 071, office: G/110
----------------------------------------------------------------------
http://www.york.ac.uk/docs/disclaimer/email.htm

**Comment by beloglazov** [comment]
Great, I'm glad it works better now!
